import { ComponentType } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import tw from 'twin.macro'

import { Home as ContainerHome } from '@/layouts/container/home'

import red from '../../public/images/rectangle-red.png'

const Home: NextPage & { Layout: ComponentType } = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div
        css={tw`flex flex-col-reverse items-center mt-20 lg:flex-row lg:justify-between lg:space-x-6`}
      >
        <p
          css={tw`max-w-3xl text-fore-primary text-xl font-serif mt-10 lg:mt-0 sm:text-2xl sm:text-left md:text-center lg:text-left`}
        >
          HI, I AM RENDI, I AM FRONTEND & BUSINESS INTELLIGENT DEVELOPER WITH
          INTEREST IN MODERN WEB DEVELOPMENT.
        </p>
        <div css={tw`relative`}>
        <div
          css={tw`absolute top-0 flex items-center justify-center w-full h-full`}
        >
          <div
            css={tw`w-32 h-32 overflow-hidden rounded-full md:h-40 md:w-40 lg:h-48 lg:w-48`}
          >
            <Image
              src={red}
              alt="My avatar"
              width={256}
              height={256}
              quality={100}
              priority={true}
              placeholder="blur"
            />
          </div>
        </div>
        </div>
      </div> */}
      <h2 tw="text-primary">HI, I AM RENDI, I AM FRONTEND &</h2>
      <h2>BUSINESS INTELLIGENT DEVELOPER</h2>
      <h2>WITH INTEREST IN MODERN</h2>
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <h2>WEB DEVELOPMENT.</h2>
    </div>
  )
}

Home.Layout = ContainerHome

export default Home
